name: debug
phase: train
gpu_ids: [0]

# Adding IR to the input
ir: True

# Path for logs and checkpoints
path:
  log: "logs"
  tb_logger: "tb_logger"
  results: "results"
  checkpoint: "checkpoint"
  # resume_state: null
  resume_state: /home/allen/Documents/MIE288/sr3_server4/E96

# Dataset settings
datasets:
  train:
    name: jenny_ir_synth
    # mode: HR
    dataroot: "data/dark/jenny_train_256_256_gamma_1.3_1.5"
    # l_resolution: 256
    # r_resolution: 256
    batch_size: 2
    num_workers: 8
    shuffle: True
    data_len: 190
    norm:
      # hr_mean: [0.5, 0.5, 0.5]
      # hr_std: [0.5, 0.5, 0.5]
      lr_mean: [0.0789, 0.0594, 0.0520]
      lr_std: [0.0754, 0.0638, 0.0614]
      ir_mean: [0.44, 0.44, 0.44]
      ir_std: [0.1, 0.1, 0.1]

  val:
    name: jenny_ir_synth
    # mode: LRHR
    dataroot: "data/dark/jenny_train_256_256_gamma_1.3_1.5"
    # l_resolution: 256
    # r_resolution: 256
    batch_size: 1
    data_len: 1
    norm:
      hr_mean: [0.5, 0.5, 0.5]
      hr_std: [0.5, 0.5, 0.5]
      lr_mean: [0.0789, 0.0594, 0.0520]
      lr_std: [0.0754, 0.0638, 0.0614]
      ir_mean: [0.44, 0.44, 0.44]
      ir_std: [0.1, 0.1, 0.1]

# Model architecture
model:
  which_model_G: ddpm
  finetune_norm: False
  torch_compile: False

  unet:
    in_channel: 9
    out_channel: 3
    inner_channel: 64
    norm_groups: 16
    channel_multiplier: [1,2,4,8,16]
    attn_res: [16]
    res_blocks: 1
    dropout: 0
  
  beta_schedule:
    train:
      schedule: cosine
      n_timestep: 1000
      linear_start: !!float 1e-6
      linear_end: !!float 1e-2
    val:
      schedule: cosine
      n_timestep: 100
      linear_start: !!float 1e-6
      linear_end: !!float 1e-2      
      
  diffusion:
    channels: 3
    conditional: True
  

# Training
train:
  grad_accum: 1
  n_iter: 1000000
  val_epoch_freq: 1
  save_ckpt_epoch_freq: 1
  print_freq: 1

  optimizer:
    type: "adam"
    lr: !!float 3e-6
  
  ema_scheduler:
    step_start_ema: 5000
    update_ema_every: 1
    ema_decay: 0.9999