name: debug
phase: train
gpu_ids: [0]

# Path for logs and checkpoints
path:
  log: "logs"
  tb_logger: "tb_logger"
  results: "results"
  checkpoint: "checkpoint"
  resume_state: null

# Dataset settings
datasets:
  train:
    name: FFHQ
    # mode: HR
    dataroot: "data/dark/ffhq_256_256_gamma_1.5_1.7"
    # l_resolution: 256
    # r_resolution: 256
    batch_size: 3
    num_workers: 8
    shuffle: True
    data_len: 190
  val:
    name: CelebaHQ
    # mode: LRHR
    dataroot: "data/dark/celebahq_256_256_gamma_1.5_1.7"
    # l_resolution: 256
    # r_resolution: 256
    batch_size: 1
    data_len: 1

# Model architecture
model:
  which_model_G: ddpm
  finetune_norm: False
  torch_compile: False

  unet:
    in_channel: 6
    out_channel: 3
    inner_channel: 64
    norm_groups: 16
    channel_multiplier: [1,2,4,8,16]
    attn_res: [16]
    res_blocks: 1
    dropout: 0
  
  beta_schedule:
    train:
      schedule: cosine
      n_timestep: 1000
      linear_start: !!float 1e-6
      linear_end: !!float 1e-2
    val:
      schedule: cosine
      n_timestep: 100
      linear_start: !!float 1e-6
      linear_end: !!float 1e-2      
      
  diffusion:
    channels: 3
    conditional: True
  

# Training
train:
  grad_accum: 1
  n_iter: 1000000
  val_epoch_freq: 1
  save_ckpt_epoch_freq: 1
  print_freq: 1

  optimizer:
    type: "adam"
    lr: !!float 2e-5
  
  ema_scheduler:
    step_start_ema: 5000
    update_ema_every: 1
    ema_decay: 0.9999