name: debug
phase: train
gpu_ids: [0]

# Adding IR to the input
ir: True

# Path for logs and checkpoints
path:
  log: "logs"
  tb_logger: "tb_logger"
  results: "results"
  checkpoint: "checkpoint"
  resume_state: null
  # resume_state: /home/allen/Documents/MIE288/sr3_server4/E146

# Dataset settings
datasets:
  train:
    name: m3fd_detection
    # mode: HR
    dataroot: "data/fuse/m3fd_detect_256_192"
    batch_size: 2
    num_workers: 8
    shuffle: True
    data_len: 16
    norm:
      hr_mean: [0.5, 0.5, 0.5]
      hr_std: [0.5, 0.5, 0.5]
      lr_mean: [0.503, 0.507, 0.492]
      lr_std: [0.189, 0.193, 0.207]
      ir_mean: [0.33, 0.33, 0.33]
      ir_std: [0.198, 0.198, 0.198]

  val:
    name: m3fd_fusion
    # mode: LRHR
    dataroot: "data/fuse/m3fd_fusion_256_192"
    # l_resolution: 256
    # r_resolution: 256
    batch_size: 1
    data_len: 20
    norm:
      hr_mean: [0.5, 0.5, 0.5]
      hr_std: [0.5, 0.5, 0.5]
      lr_mean: [0.503, 0.507, 0.492]
      lr_std: [0.189, 0.193, 0.207]
      ir_mean: [0.33, 0.33, 0.33]
      ir_std: [0.198, 0.198, 0.198]


# Model architecture
model:
  which_model_G: ddpm
  finetune_norm: False
  torch_compile: False

  unet:
    in_channel: 7  # RGB + IR + Noise
    out_channel: 3
    inner_channel: 160
    norm_groups: 16
    channel_multiplier: [1,1,2,2,4,4]
    attn_res: [8,16,32]
    res_blocks: 2
    dropout: 0
  
  beta_schedule:
    train:
      schedule: cosine
      n_timestep: 1000
      linear_start: !!float 1e-6
      linear_end: !!float 1e-2
    val:
      schedule: cosine
      n_timestep: 100
      ddim_timestep: 20
      linear_start: !!float 1e-6
      linear_end: !!float 1e-2      
      
  diffusion:
    channels: 3
    conditional: True
  

# Training
train:
  grad_accum: 1
  n_iter: 1000000
  val_epoch_freq: 1
  save_ckpt_epoch_freq: 1
  print_freq: 1

  optimizer:
    type: "adam"
    lr: !!float 2e-5
  
  ema_scheduler:
    ema_start: 5000
    update_ema_every: 1
    ema_decay: 0.9999