name: infer
phase: test
gpu_ids: [2]

# Path for logs and checkpoints
path:
  log: "logs"
  tb_logger: "tb_logger"
  results: "results"
  checkpoint: "checkpoint"
  resume_state: ffhq_256_25M_E270

# Dataset settings
datasets:
  test:
    name: infer
    dataroot: "data/dark/celebahq_256_256_gamma_1.5_1.7"
    batch_size: 1
    data_len: 20

# Model architecture
model:
  which_model_G: ddpm
  finetune_norm: False
  torch_compile: True

  unet:
    in_channel: 6
    out_channel: 3
    inner_channel: 128
    norm_groups: 32
    channel_multiplier: [1,1,2,2,4,4]
    attn_res: [8,16,32]
    res_blocks: 1
    dropout: 0
  
  beta_schedule:
    test:
      schedule: cosine
      n_timestep: 1000
      ddim_timestep: 100
      linear_start: !!float 1e-6
      linear_end: !!float 1e-2      
      
  diffusion:
    channels: 3
    conditional: True
  