name: INFER_m3fd_6M_512
phase: test
gpu_ids: [7]

# Adding IR to the input
ir: True

# Path for logs and checkpoints
path:
  log: "logs"
  tb_logger: "tb_logger"
  results: "results"
  checkpoint: "checkpoint"
  # resume_state: null
  resume_state: /home/allen/Documents/MIE288/sr3_server4/m3fd_512_6M_E825

# Dataset settings
datasets:
  test:
    name: m3fd_detection
    dataroot: "data/fuse/m3fd_fusion_512_384"
    batch_size: 1
    data_len: -1
    norm:
      lr_mean: [0.503, 0.507, 0.492]
      lr_std: [0.189, 0.193, 0.207]
      ir_mean: [0.33]
      ir_std: [0.198]

# Model architecture
model:
  which_model_G: ddpm
  finetune_norm: False
  torch_compile: True

  unet:
    # in_channel: 9  # RGB + IR + Noise
    in_channel: 7  # RGB + IR + Noise
    out_channel: 3
    inner_channel: 64
    norm_groups: 16
    channel_multiplier: [1,1,2,2,4,4]
    attn_res: [8,16,32]
    res_blocks: 1
    dropout: 0
  
  beta_schedule:
    test:
      schedule: cosine
      n_timestep: 1000
      linear_start: !!float 1e-6
      linear_end: !!float 1e-2      
      
  diffusion:
    channels: 3
    conditional: True
  