name: infer_ir_E1300_jenny_real
phase: test
gpu_ids: [6]

# Adding IR to the input
ir: True

# Path for logs and checkpoints
path:
  log: "logs"
  tb_logger: "tb_logger"
  results: "results"
  checkpoint: "checkpoint"
  # resume_state: null
  resume_state: /home/allen/Documents/MIE288/sr3_server4/experiments/jenny_ir_rgb_256_adamW_230926_154117/checkpoint/E1300

# Dataset settings
datasets:
  test:
    name: jenny_ir_real
    dataroot: "data/dark/jenny_test_256_256"
    batch_size: 1
    data_len: -1
    norm:
      lr_mean: [0.0789, 0.0594, 0.0520]
      lr_std: [0.0754, 0.0638, 0.0614]
      ir_mean: [0.44, 0.44, 0.44]
      ir_std: [0.1, 0.1, 0.1]

# Model architecture
model:
  which_model_G: ddpm
  finetune_norm: False
  torch_compile: True

  unet:
    in_channel: 9
    out_channel: 3
    inner_channel: 64
    norm_groups: 16
    channel_multiplier: [1,2,4,8,16]
    attn_res: [16]
    res_blocks: 1
    dropout: 0
  
  beta_schedule:
    test:
      schedule: cosine
      n_timestep: 1000
      linear_start: !!float 1e-6
      linear_end: !!float 1e-2      
      
  diffusion:
    channels: 3
    conditional: True
  