name: infer_E170_jenny_rgb_real
phase: test
gpu_ids: [2]

# Path for logs and checkpoints
path:
  log: "logs"
  tb_logger: "tb_logger"
  results: "results"
  checkpoint: "checkpoint"
  # resume_state: /home/allen/Documents/MIE288/sr3_server4/experiments/jenny_rgb_norm_adamW_230925_122501/checkpoint/I142968_E120
  resume_state: /home/allen/Documents/MIE288/sr3_server4/experiments/jenny_rgb_norm_adamW_230925_122501/checkpoint/I149018_E170

# Dataset settings
datasets:
  test:
    name: infer
    dataroot: "data/dark/jenny_256_256"
    # dataroot: "data/dark/LOLv2-eval_256_256"
    batch_size: 1
    data_len: -1

# Model architecture
model:
  which_model_G: ddpm
  finetune_norm: False
  torch_compile: True

  unet:
    in_channel: 6
    out_channel: 3
    inner_channel: 64
    norm_groups: 16
    channel_multiplier: [1,2,4,8,16]
    attn_res: [16]
    res_blocks: 1
    dropout: 0
  
  beta_schedule:
    test:
      schedule: cosine
      n_timestep: 1000
      linear_start: !!float 1e-6
      linear_end: !!float 1e-2      
      
  diffusion:
    channels: 3
    conditional: True
  